/*
 * The typings-manifest pipeline (spec §2(l)): extracts every declared name from
 * types/vacuus.d.ts into a deterministic JSON manifest, committed at
 * Content/DevUI/Tests/vacuus-api-manifest.json. The in-engine conformance test
 * walks the real prototypes/globals against it BOTH WAYS; this module's
 * `--check` half fails the node-side smoke when the committed file is stale
 * against the .d.ts. The group semantics are the .d.ts header's extraction
 * contract — change one, change both.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

/** interface name -> manifest group (the .d.ts extraction contract). */
const INTERFACE_GROUPS = {
	VaCuusElement: 'element',
	VaCuusDocument: 'document',
	VaCuusClassList: 'classList',
	VaCuusConsole: 'console',
	VaCuusHost: 'vacuus',
};

const MEMBER_RE = /^\s*(?:readonly\s+)?([A-Za-z_$][A-Za-z0-9_$]*)(\??)\s*[:(]/;

/**
 * Comments go first: the .d.ts prose legally contains unbalanced braces
 * (RmlUi's `{{` expression syntax comes up a lot), which would corrupt the
 * brace-counted interface bodies below, and a doc line could false-positive the
 * member regex. No string literals exist outside comments in a .d.ts of this
 * shape, so two regexes suffice.
 */
function stripComments(source) {
	return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

/** Pulls the `{ ... }` body of `interface <name>` by brace counting. */
function interfaceBody(source, name) {
	const declMatch = source.match(new RegExp(`interface\\s+${name}\\b[^{]*\\{`));
	if (!declMatch) throw new Error(`vacuus.d.ts: interface ${name} not found`);
	let depth = 1;
	const start = declMatch.index + declMatch[0].length;
	for (let i = start; i < source.length; ++i) {
		if (source[i] === '{') ++depth;
		else if (source[i] === '}' && --depth === 0) return source.slice(start, i);
	}
	throw new Error(`vacuus.d.ts: interface ${name} never closes`);
}

/** Member names of an interface body; index signatures ([x: string]) are skipped. */
function members(body) {
	const required = [];
	const optional = [];
	const methods = [];
	for (const line of body.split('\n')) {
		const m = line.match(MEMBER_RE);
		if (!m) continue;
		const [, name, opt] = m;
		const isMethod = line.slice(line.indexOf(name) + name.length + opt.length).trimStart().startsWith('(');
		if (opt === '?') optional.push(name);
		else if (isMethod) methods.push(name);
		else required.push(name);
	}
	return { required, optional, methods };
}

export function extractManifest(dtsPath) {
	const source = stripComments(readFileSync(dtsPath, 'utf8'));
	const groups = {};

	for (const [iface, group] of Object.entries(INTERFACE_GROUPS)) {
		const { required, optional, methods } = members(interfaceBody(source, iface));
		if (optional.length) {
			throw new Error(`vacuus.d.ts: ${iface} has optional members (${optional}); only VaCuusEvent may`);
		}
		groups[group] = [...methods, ...required].sort();
	}

	// VaCuusEvent splits three ways (the extraction contract): methods live on the
	// event prototype, required props on every instance, optional props are the
	// conditional per-dispatch aliases, recorded as excluded-by-design below.
	const ev = members(interfaceBody(source, 'VaCuusEvent'));
	groups.eventPrototype = [...ev.methods].sort();
	groups.eventInstance = [...ev.required].sort();

	// Globals: `declare var|function NAME`.
	const globals = [];
	for (const m of source.matchAll(/^declare\s+(?:var|const|function)\s+([A-Za-z_$][A-Za-z0-9_$]*)/gm)) {
		globals.push(m[1]);
	}
	groups.globals = globals.sort();

	return {
		format: 1,
		source: 'Web/packages/cli/types/vacuus.d.ts',
		note: 'Generated by `vacuus manifest`. Do not edit by hand — the smoke script fails when this file is stale against the .d.ts, and the in-engine conformance test walks the real prototypes against it both ways.',
		groups,
		excluded: {
			eventAliases: {
				names: ev.optional.sort(),
				reason: 'Per-dispatch conditional: each exists only when the RmlUi event carried the matching parameter (VaCuusJsEvents.cpp:258-284), so no single dispatch can enumerate them all.',
			},
			style: {
				reason: 'element.style mints a fresh JS Proxy per access; own-key enumeration is trap-defined, not prototype truth. Typed as VaCuusStyle, verified behaviorally by VaCuus.Js.Dom.StyleCamelCase.',
			},
			globalScan: {
				reason: 'globalThis own-props include the entire QuickJS ES intrinsic surface (Object, Math, Promise, queueMicrotask, ...), which is the TS lib\'s domain, not this manifest\'s — so the globals group is verified typed->present only. A facade global added without typing escapes this walk; InstallGlobals (VaCuusJsViewContext.cpp) is the one function to review when adding one.',
			},
		},
	};
}

export function manifestJson(manifest) {
	return JSON.stringify(manifest, null, 2) + '\n';
}

/** Write (default) or --check. Returns process exit code. */
export function runManifest(dtsPath, outPath, check) {
	const fresh = manifestJson(extractManifest(dtsPath));
	if (check) {
		if (!existsSync(outPath)) {
			console.error(`STALE: ${outPath} does not exist; run \`vacuus manifest\``);
			return 1;
		}
		const committed = readFileSync(outPath, 'utf8');
		if (committed !== fresh) {
			console.error(`STALE: ${outPath} does not match ${dtsPath}; run \`vacuus manifest\` and commit the result`);
			return 1;
		}
		console.log(`manifest up to date: ${outPath}`);
		return 0;
	}
	writeFileSync(outPath, fresh);
	console.log(`wrote ${outPath}`);
	return 0;
}
