[FilterPlugin]
; This section lists additional files which will be packaged for distribution. Paths should be listed relative to the
; root plugin directory, and may include "...", "*", and "?" wildcards to match directories, files, and individual
; characters respectively.
;
; Examples:
;    /README.txt
;    /Extras/...
;    /Binaries/ThirdParty/*.dll
