#!/usr/bin/env bash
# Regenerates Private/Gen/relay_*.cpp — one relay TU per vendored RmlUi Core .cpp.
# UBT only compiles sources inside the module directory, so each vendored .cpp
# gets a relay TU that #includes it. Re-run only when the vendored SHA changes,
# then commit the result.
# Requires GNU coreutils (uses `realpath --relative-to`).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; RML="$ROOT/../ThirdParty/RmlUi/Source"
[ -d "$RML/Core" ] || { echo "gen_relays.sh: $RML/Core not found" >&2; exit 1; }
git -C "$ROOT/.." status --porcelain -- Source/ThirdParty/RmlUi/Source/Core | grep -q . && echo 'warning: dirty vendor tree' >&2 || true
OUT="$ROOT/Private/Gen"; rm -rf "$OUT"; mkdir -p "$OUT"
find "$RML/Core" -name '*.cpp' | sort | while read -r f; do
  rel="$(realpath --relative-to="$OUT" "$f")"
  base="${f#"$RML"/}"; base="${base%.cpp}"; name="$(echo "$base" | tr '/' '_')"
  if [ -e "$OUT/relay_${name}.cpp" ]; then
    echo "collision: $name" >&2
    exit 1
  fi
  {
    printf '// Auto-generated by gen_relays.sh — do not edit.\n'
    printf '#include "%s"\n' "$rel"
  } > "$OUT/relay_${name}.cpp"
done
n=$(find "$OUT" -maxdepth 1 -name 'relay_*.cpp' | wc -l); [ "$n" -gt 0 ] || { echo "gen_relays.sh: generated 0 relay TUs" >&2; exit 1; }
echo "generated $(ls "$OUT" | wc -l) relay TUs"
