#!/usr/bin/env bash
# Regenerates Private/Gen/relay_*.c — one relay TU per vendored quickjs-ng .c.
# UBT only compiles sources inside the module directory, so each vendored .c
# gets a relay TU that #includes it (the VaCuusRml/gen_relays.sh pattern; the
# engine's own vendored-C precedent is SQLiteCore/Private/SQLiteEmbedded.c).
# Re-run only when the vendored SHA changes, then commit the result.
# Requires GNU coreutils (uses `realpath --relative-to`).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; QJS="$ROOT/../ThirdParty/quickjs-ng"
[ -f "$QJS/quickjs.c" ] || { echo "gen_relays.sh: $QJS/quickjs.c not found" >&2; exit 1; }
git -C "$ROOT/../.." status --porcelain -- Source/ThirdParty/quickjs-ng | grep -q . && echo 'warning: dirty vendor tree' >&2 || true
OUT="$ROOT/Private/Gen"; rm -rf "$OUT"; mkdir -p "$OUT"
for f in "$QJS"/*.c; do
  rel="$(realpath --relative-to="$OUT" "$f")"
  name="$(basename "$f" .c)"
  {
    printf '// Auto-generated by gen_relays.sh — do not edit.\n'
    # MSVC only, and the first Win64 build is what put it here. UBT compiles every module
    # with /W4 /WX and a module CANNOT opt out: UEBuildModuleCPP.cs:2669 ORs the flag in
    # (`Result.bWarningsAsErrors |= Rules.bWarningsAsErrors`), so VaCuusJs.Build.cs's
    # `bWarningsAsErrors = false` is inert. MSVC's back end then raises C4702 (unreachable
    # code) inside vendored quickjs.c -- at :665 strv, :3074 JS_AtomGetKind, :23606
    # find_var_htab, :52215 get_first_weak_ref -- and /WX turns each into an error. These
    # are code-generation warnings, so no include-path flag reaches them (/external:W0
    # covers headers, and this is a .c being compiled); the pragma has to be in the TU.
    #
    # Scoped to the relay, which is exactly what the relay is for: the vendored .c is not
    # edited, and our own C would still be held to /W4 /WX. clang is unaffected -- it does
    # not raise C4702 and would warn on the unknown pragma, hence the _MSC_VER guard.
    printf '#if defined(_MSC_VER) && !defined(__clang__)\n'
    printf '#pragma warning(disable : 4702) // unreachable code, in vendored quickjs-ng\n'
    printf '#endif\n'
    printf '#include "%s"\n' "$rel"
  } > "$OUT/relay_${name}.c"
done
# The core library is exactly four TUs (quickjs-ng CMakeLists.txt:266-271);
# a fifth .c in the vendored tree means the vendoring itself went wrong.
n=$(find "$OUT" -maxdepth 1 -name 'relay_*.c' | wc -l)
[ "$n" -eq 4 ] || { echo "gen_relays.sh: expected 4 relay TUs, generated $n" >&2; exit 1; }
echo "generated $n relay TUs"
