#!/usr/bin/env bash
# Regenerates Private/Gen/relay_*.c — one relay TU per vendored quickjs-ng .c.
# UBT only compiles sources inside the module directory, so each vendored .c
# gets a relay TU that #includes it (the VaCuusRml/gen_relays.sh pattern; the
# engine's own vendored-C precedent is SQLiteCore/Private/SQLiteEmbedded.c).
# Re-run only when the vendored SHA changes, then commit the result.
# Requires GNU coreutils (uses `realpath --relative-to`).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; QJS="$ROOT/../ThirdParty/quickjs-ng"
[ -f "$QJS/quickjs.c" ] || { echo "gen_relays.sh: $QJS/quickjs.c not found" >&2; exit 1; }
git -C "$ROOT/../.." status --porcelain -- Source/ThirdParty/quickjs-ng | grep -q . && echo 'warning: dirty vendor tree' >&2 || true
OUT="$ROOT/Private/Gen"; rm -rf "$OUT"; mkdir -p "$OUT"
for f in "$QJS"/*.c; do
  rel="$(realpath --relative-to="$OUT" "$f")"
  name="$(basename "$f" .c)"
  {
    printf '// Auto-generated by gen_relays.sh — do not edit.\n'
    printf '#include "%s"\n' "$rel"
  } > "$OUT/relay_${name}.c"
done
# The core library is exactly four TUs (quickjs-ng CMakeLists.txt:266-271);
# a fifth .c in the vendored tree means the vendoring itself went wrong.
n=$(find "$OUT" -maxdepth 1 -name 'relay_*.c' | wc -l)
[ "$n" -eq 4 ] || { echo "gen_relays.sh: expected 4 relay TUs, generated $n" >&2; exit 1; }
echo "generated $n relay TUs"
